[features]
seeds = false
[programs.devnet]
soltribe = "Hw5exfHf8wV8yaCETfJTdTCmkeDotsJsn8biptSd8pM7"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
